version: '3.1'

services:
  db:
    image: postgres
    restart: 'no'
    volumes:
     - .volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: spring
      POSTGRES_DB: spring
    ports:
     - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
